# Site settings
title: Forrest Bradley
description: > # this means to ignore newlines until "baseurl:"
  My name is Forrest and I'm a MEAN developer in the San Francisco Bay Area. This online portfolio demos some of my private and open source projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.forrestbradley.com"
twitter_username: fbradley8
github_username:  fbradley8

# Build settings
markdown: kramdown
host: 0.0.0.0